Feat: Gas price config value
fuseio/fuseswap-interface pull request #20
Opened 2021-01-04 13:13 UTC by mul53

- Add gas price as a config value

2021-01-04 14:14 UTC, leonprou approved these changes
@mul53 looks good. The gas price is given only on Fuse, right?

2021-01-04 14:16 UTC, leonprou requested changes
One more thing, can you fix the failing test?

2021-01-04 20:46 UTC, mul53 commented
@leonprou  yes, it's only added on the fuse network, on pages we use the isHome value to determine whether to add and on the bridges i set it in transferToForeign

2021-01-05 10:07 UTC, leonprou approved these changes

2021-01-05 10:07 UTC, merged